import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import { Footer } from "@/components/Footer/Footer";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "AbeloHost test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={montserrat.className}>
      <body>
        <Header />
        <div
          className="container"
          style={{ paddingTop: "calc(var(--height-top) + var(--height-bottom))" }}
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
